export const AUDIT_EVENT_TYPES = [
    "LOGIN",
    "USER",
    "EMPLOYEE",
    "TIMESHEET",
    "ANNOUNCEMENT",
    "LOCATION_UNIT",
    "SETTINGS",
    "SECURITY"
];

export const AUDIT_EVENT_LABELS = {
    LOGIN: "GİRİŞ",
    USER: "KULLANICI",
    EMPLOYEE: "ÇALIŞAN",
    TIMESHEET: "PUANTAJ",
    ANNOUNCEMENT: "DUYURU",
    LOCATION_UNIT: "YERLEŞKE/BİRİM",
    SETTINGS: "AYARLAR",
    SECURITY: "GÜVENLİK"
};