// LOG TYPE (Domain Bazlı)
export const LOG_TYPE = Object.freeze({
  AUTH: "AUTH",
  USER: "USER",
  EMPLOYEE: "EMPLOYEE",
  TIMESHEET: "TIMESHEET",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  SYSTEM: "SYSTEM",
  SECURITY: "SECURITY",
});

// LOG ACTION (Spesifik Olaylar)
export const LOG_ACTION = Object.freeze({

  // AUTH
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",

  // USER
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_SCOPE_CHANGED: "USER_SCOPE_CHANGED",

  // EMPLOYEE
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",

  // TIMESHEET
  TIMESHEET_CREATED: "TIMESHEET_CREATED",
  TIMESHEET_UPDATED: "TIMESHEET_UPDATED",
  TIMESHEET_DELETED: "TIMESHEET_DELETED",

  // ANNOUNCEMENT
  ANNOUNCEMENT_CREATED: "ANNOUNCEMENT_CREATED",
  ANNOUNCEMENT_UPDATED: "ANNOUNCEMENT_UPDATED",
  ANNOUNCEMENT_DELETED: "ANNOUNCEMENT_DELETED",

  // SYSTEM
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  PERIOD_CREATED: "PERIOD_CREATED",
  PERIOD_UPDATED: "PERIOD_UPDATED",
  PERIOD_CLOSED: "PERIOD_CLOSED",

  // SECURITY
  UNAUTHORIZED_ACCESS_ATTEMPT: "UNAUTHORIZED_ACCESS_ATTEMPT",
});